"""initial schema

Baseline migration for a greenfield database. It builds every table directly
from the SQLAlchemy metadata (Postgres ENUM types included), so the schema always
matches the models. Once the project has real users, switch to granular
autogenerated migrations for subsequent changes.

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-07
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op

from app.db import Base
import app.models  # noqa: F401  (register all tables on Base.metadata)

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
